### ISSUE TITLE
Google Calendar Support

### ISSUE THREAD

**Issue by DadBackFromWalmart** [OneThatWalks/anker-discord-bot#5]
**Is your feature request related to a problem? Please describe.**
Anna uses Goggle Calendar to create the month's work schedule. Instead of having to add events manually, one by one, it would be nice to have the bot sync up with Google Calendar, so that the !schedule commands pulls straight from the Google Calendar events.

**Describe the solution you'd like**
I do not know how this would be achieved.

**Describe alternatives you've considered**
An alternative (which I'm actually going to create as its own feature request, as both would be nice) would be Manual Event Adding - the ability to !add, !remove, or !edit manual events for on the fly adds / edits to the schedule.

**Additional context**
'!schedule' would show all events for that user, '!schedule all' would show the schedule for all users, and '!schedule @user' would show schedule for someone else. These commands would show events that are scheduled in the Google Calendar. '!schedule month' would show the whole month's schedule as either a text block or image.

**Comment by OneThatWalks** [comment]
@DadBackFromWalmart currently I am using google calendar.  I've just recently finished abstracting the api interaction layer so we could switch to anything that had an API relatively easily.

The code is [here](https://github.com/OneThatWalks/anker-discord-bot/blob/master/src/services/google-api.ts)

What is important is that discord id's are tied to attendee email addresses.  I will update this later with more information about how I have it configured and how we would migrate to Anna's google or otherwise.

**Comment by OneThatWalks** [comment]
Marking as closed. We can reference this issue if there are problems migrating.
